### ISSUE TITLE
Cant Downloand Setup .exe file

### ISSUE THREAD

**Issue by DleckYT** [ImAxel0/Openthesia#1]
https://github.com/ImAxel0/Openthesia/assets/172240241/fa2626bb-aecc-48f8-a503-eb45a8b9ec4b

its may be a windows problem but I often dont have this problem when downloading applications if you could help that would be great

**Comment by ImAxel0** [comment]
Never had this exact problem with any other application so I don't really have a solution, I can leave the installed application folder here so you should be able to move it somewhere and run the app from Openthesia.exe
[Openthesia 1.2.0.zip](https://github.com/user-attachments/files/15766391/Openthesia.1.2.0.zip)

**Comment by DleckYT** [comment]
Thanks for sending in the zip file and it works i can use your app

**Comment by DleckYT** [comment]
Is it possible to change soundfonts?
