### ISSUE TITLE
Auto-Assign Colors per Track of Imported MIDI

### ISSUE THREAD

**Issue by KeronCyst** [ImAxel0/Openthesia#3]
For MIDI files that use multiple MIDI tracks, it'd be great to be able to see Openthesia auto-assign colors from a list in settings (like track 2 could be cyan, etc.) instead of starting them all as right-hand/green. As far as I know, MIDI files can support up to 16 tracks, and track 10 is always percussion, so seeing this differentiation would be great.

**Comment by ImAxel0** [comment]
I not really familiar with this, also I would have to look what the midi library can do about it. 
I may give a look in future.
