### ISSUE TITLE
MIDI file-open screen still animates background even if disabled in settings

### ISSUE THREAD

**Issue by KeronCyst** [ImAxel0/Openthesia#4]
1. Uncheck the "Animated background" checkbox in the settings
2. Load a MIDI file and get to the "Peacefully listen and visualize the piece" screen

Current outcome: the background inside this window animates with rapid-fire notes

Expected outcome: the background would have no such animations

**Comment by ImAxel0** [comment]
This was a voluntary choice since it looked a bit off without it. I will disable it the next time.
