### ISSUE TITLE
Cannot pick text-display options other than Velocity

### ISSUE THREAD

**Issue by KeronCyst** [ImAxel0/Openthesia#5]
On Windows 10 in 1920×1080 resolution:

1. Start playing a MIDI file
2. Hover your mouse over the ~~T~~ graphic

The popup showing "NoteName," "Velocity," and "Octave" is hundreds of pixels down, so that you can't mouse over to it and toggle anything other than Velocity because the gap causes the popup to disappear.

![image](https://github.com/ImAxel0/Openthesia/assets/13827055/dd9e71d4-1de3-45fb-82d2-3b8e119fb1db)

**Comment by ImAxel0** [comment]
You actually can by scrolling with the mouse while the menu is shown (the speed change control will be ignored). Anyway it's my fault since I still haven't updated the documentation for the latest version.

**Comment by KeronCyst** [comment]
Apparently in 1080p the colors in the upper-left also close, because there is a tiny gap that the mouse has to pass between the button and the color window. It would be nice if the button was a toggle that forces these popups to stay open until the button is clicked again. Currently, the only way to change the hand colors is in the settings.

**Comment by ImAxel0** [comment]
While I agree that it should stay open you can always temporarily lock the top bar and freely change the colors

**Comment by KeronCyst** [comment]
Oh, I just saw the lock icon! Haha, I didn't know what it did. It would be nice to have tooltips appear over these buttons when moused over for long enough. Thanks.
