### ISSUE TITLE
TopBar is little to small

### ISSUE THREAD

**Issue by ArBom** [ImAxel0/Openthesia#7]
![obraz_2024-11-14_231127391](https://github.com/user-attachments/assets/797eb9c3-c95e-4b92-b3d9-ddd39f53ed22)
With open lock (1. at screen) is impossible to change speed with bottom list (2.);

After change 679. line at ScreenCanvas.cs to "var showTopBar = ImGui.IsMouseHoveringRect(Vector2.Zero, new(ImGui.GetIO().DisplaySize.X, **200**));" is OK

That's really great app.

**Comment by ImAxel0** [comment]
I added the change and also made sure top bar isn't hidden when colors or combo box controls are opened.
